/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab01;

class SmartHomeController {

    private int temp;
    private boolean restrict;

	/** <code>SmartHomeController</code> should not normally be instantiated. */
	public SmartHomeController(int temp, boolean restrict) {
        this.temp = temp;
        this.restrict = restrict;
        
	}
	
    public int getTemp(){
        return this.temp;
    }

    public int setTemp(int temp){
        if(!restrict){
            this.temp = temp;
        } else {
            if(temp >= 20 && temp <= 26){
                this.temp = temp;
            }
        }
        return this.temp;
    }
    public boolean getRestrictions(){
        return this.restrict;
    }
    public boolean setRestrictions(boolean val) {
        return this.restrict = val;
    }
}